language: java
sudo: false
notifications:
  slack: "blazebit:$SLACK_API_TOKEN"
cache:
  directories:
    - '$HOME/.m2/repository'
before_install:
  - sh -c "if [ '$RDBMS' = 'firebird' ]; then sh travis/before_install_firebird.sh; fi"
install:
# Skip the first maven execution for downloading dependencies by using this command
  - /bin/true
before_script:
  - sh -c "if [ '$RDBMS' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;'; fi"
  - sh -c "if [ '$RDBMS' = 'postgresql' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$RDBMS' = 'db2' ]; then sh travis/before_script_db2.sh; fi"
  - sh -c "if [ '$RDBMS' = 'firebird' ]; then sh travis/before_script_firebird.sh; fi"
  - sh -c "if [ '$RDBMS' = 'oracle' ]; then sh travis/before_script_oracle.sh; fi"
  - sh -c "if [ '$RDBMS' = 'mssql' ]; then sh travis/before_script_mssql.sh; fi"
after_failure: 
  - sh travis/print_surefire_reports.sh
script:
  - ./build.sh
after_success:
  - "bash ./.travis-deploy.sh"
env:
  global:
    - MAVEN_SKIP_RC=true
matrix:
  fast_finish: true
  include:
################################################
# hibernate-5.2
################################################
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 SPRING_DATA=spring-data-2.0.x DELTASPIKE=deltaspike-1.8
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 SPRING_DATA=spring-data-2.1.x DELTASPIKE=deltaspike-1.8
      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.2 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.2 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# datanucleus-5
################################################
    - env: JPAPROVIDER=datanucleus-5 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=datanucleus-5 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=datanucleus-5 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=mssql
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=db2
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# eclipselink
################################################
    - env: JPAPROVIDER=eclipselink RDBMS=h2
      jdk: oraclejdk8
#    - env: JPAPROVIDER=eclipselink RDBMS=mysql
#      dist: trusty
#      sudo: required
#    - env: JPAPROVIDER=eclipselink RDBMS=postgresql
#      addons:
#        postgresql: "9.3"
#    - env: JPAPROVIDER=eclipselink RDBMS=mssql
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=eclipselink RDBMS=db2
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=eclipselink RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=eclipselink RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=eclipselink RDBMS=firebird
#      sudo: true

################################################
# openjpa
################################################
#    - env: JPAPROVIDER=openjpa RDBMS=h2
#    - env: JPAPROVIDER=openjpa RDBMS=mysql
#      dist: trusty
#      sudo: required
#    - env: JPAPROVIDER=openjpa RDBMS=postgresql
#      addons:
#        postgresql: "9.3"
#    - env: JPAPROVIDER=openjpa RDBMS=mssql
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=openjpa RDBMS=db2
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=openjpa RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=openjpa RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=openjpa RDBMS=firebird
#      sudo: true

################################################
# hibernate-5.3
################################################
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
#    - env: JPAPROVIDER=hibernate-5.3 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.3 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true
################################################
# hibernate-5.4
################################################
    - env: JPAPROVIDER=hibernate-5.4 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.4 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate-5.4 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate-5.4 RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.4 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.4 RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
#    - env: JPAPROVIDER=hibernate-5.3 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.3 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# datanucleus-5.1
################################################
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=h2
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=mysql
#      jdk: oraclejdk8
#      dist: trusty
#      sudo: required
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=postgresql
#      jdk: oraclejdk8
#      addons:
#        postgresql: "9.3"
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=mssql
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=db2
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# hibernate-5.1
################################################
    - env: JPAPROVIDER=hibernate-5.1 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.1 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate-5.1 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate-5.1 RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.1 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.1 RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
#    - env: JPAPROVIDER=hibernate-5.1 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.1 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# hibernate-5.0
################################################
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# hibernate-4.3
################################################
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=firebird
#      sudo: true

################################################
# hibernate-4.2
################################################
    - env: JPAPROVIDER=hibernate RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=hibernate RDBMS=postgresql
      jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - env: JPAPROVIDER=hibernate RDBMS=mssql
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate RDBMS=db2
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
    - env: JPAPROVIDER=hibernate RDBMS=oracle
      jdk: oraclejdk8
      sudo: true
      services:
        - docker
#    - env: JPAPROVIDER=hibernate RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate RDBMS=firebird
#      sudo: true

################################################
# datanucleus-4
################################################
    - env: JPAPROVIDER=datanucleus-4 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=datanucleus-4 RDBMS=mysql
      jdk: oraclejdk8
      dist: trusty
      sudo: required
    - env: JPAPROVIDER=datanucleus-4 RDBMS=postgresql
      addons:
        postgresql: "9.3"
      jdk: oraclejdk8
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=mssql
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=db2
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
#      services:
#        - docker
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=sqlite
#      jdk: oraclejdk8
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true

################################################
# hibernate-6.0
################################################
#    - env: JPAPROVIDER=hibernate-6.0 RDBMS=h2
#      jdk: oraclejdk8

################################################
# JDK 9+
################################################
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=10
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 10 -L GPL
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=11
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 11 -L BCL
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=12
      before_install:
      - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
      - . ./install-jdk.sh -F 12 -L GPL
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=10 BUILD_JDK=10
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 10 -L GPL
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=11 BUILD_JDK=11
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 11 -L BCL
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=12 BUILD_JDK=12
      before_install:
      - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
      - . ./install-jdk.sh -F 12 -L GPL
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=9
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 9 -L GPL
    - env: JPAPROVIDER=datanucleus-5 RDBMS=h2 JDK=9
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 9 -L GPL
    - env: JPAPROVIDER=eclipselink RDBMS=h2 JDK=9
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 9 -L GPL
    - env: JPAPROVIDER=hibernate-5.3 RDBMS=h2 JDK=9
      before_install:
        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
################################################
# Skip JDK 9 profile combinations for older JPA provider versions
################################################
#    - env: JPAPROVIDER=hibernate-5.1 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-4.2 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
  allow_failures:
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=10 BUILD_JDK=10
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=11 BUILD_JDK=11
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=11
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=12 BUILD_JDK=12
    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 JDK=12
#    - env: JPAPROVIDER=datanucleus-5.1 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-5.1 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=hibernate-4.2 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=h2 JDK=9
#      before_install:
#        - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
#        - . ./install-jdk.sh -F 9 -L GPL